### ISSUE TITLE
Keep the mouse where it was initially after Scroll Mode is done

### ISSUE THREAD

**Issue by nikitavoloboev** [dexterleng/vimac#116]
I have an issue where say I am in Discord app. I have a binding to centre my mouse to middle of the app. In Discord if I do that and then activate Scroll Mode, I can start scrolling with J and K. The problem is that the mouse moves to the bottom left corner of the screen during the process and after the process **stays** there.

I do like the fact that the mouse moves out of the way during scroll mode. However I propose to move the mouse back to original position it was in before activating scroll mode once the scroll mode is turned off (hotkey is pressed again or app was switched).

That would be wonderful. The use case is that it's annoying as sometimes in say above Discord app case. I move mouse to middle, scroll mode activate. Then disable. Then if I enable again, I am scrolling the left sidebar, not the middle of the screen as I wanted to.

Thank you.

**Comment by dexterleng** [comment]
Good idea, I will look into this.

**Comment by dexterleng** [comment]
> Then disable. Then if I enable again, I am scrolling the left sidebar, not the middle of the screen as I wanted to.

Could you elaborate? I don't quite understand how this feature would help your use case.

"Keep the mouse where it was initially after Scroll Mode is done", by "done" do you mean after it is activated or deactivated?

**Comment by dexterleng** [comment]
Are you suggesting we don't lock the mouse position or we revert the position of the cursor after scroll mode is disabled to before it was activated, or both?

**Comment by nikitavoloboev** [comment]
Ok I now realized that the mouse always goes to left corder when activating screen reader.

I thought it maybe is good to preserve the mouse location where it was before activating screen reader (and hide the mouse pointer on scrolling). That would be perfect I think.

**Comment by dexterleng** [comment]
Ah ok. The goal is to hide the cursor (and center it in the scroll area) during Scroll mode and move it back after Scroll mode has exited.

**Comment by dexterleng** [comment]
I noticed that discord's Scroll Area is quite unindicative of the area scroll area. This is the case with most electron/web apps from what I recall. This is why the cursor is positioned in the bottom-left of the entire app instead of bottom-left of the actual scroll area.

**Comment by dexterleng** [comment]
Addressed in #118 #112

**Comment by dexterleng** [comment]
feel free to reopen if it does not address the issue.
