### ISSUE TITLE
What are the performance implications of always running in screen reader mode?

### ISSUE THREAD

**Issue by nikitavoloboev** [dexterleng/vimac#117]
I am wondering this as it seems like this would cause a lot of CPU time to process everything in screen reader mode. Maybe I am wrong?

Is the effect negligible?

**Comment by dexterleng** [comment]
I assume this is a prompt you received with an Electron/Chromium app like Discord.

Webapps, unlike native mac apps, do not report UI element information (e.g. button location) until you specify you are a screen reader to them.

I've yet to do profiling, but yeah, there should be a performance impact:

https://github.com/electron/electron/issues/7206#issuecomment-267912698

**Comment by dexterleng** [comment]
I will look into disabling the screen reader mode when it is not used.

One solution I've tried is to enable the `AXManualAccessibility` attribute right before Hint/Scroll mode, there is some race condition preventing it from working.

The `AXManualAccessibility` attribute could also be set to false when the electron app is no longer front-most so it doesn't suck up battery while in the background.
