### ISSUE TITLE
Retain hint text for extra menu items

### ISSUE THREAD

**Issue by dexterleng** [dexterleng/vimac#121]
Currently it keeps changing if you enable/disable hint mode despite the content being unchanged.

**Comment by DaniBedz** [comment]
Having static hint text would definitely help users to develop muscle-memory easier when using ViMac.

Happy to see this as something that's being worked on. It's definitely one of my gripes with what otherwise is a great app. Keep up the good work! 👍

**Comment by dexterleng** [comment]
Addressed.
