### ISSUE TITLE
install via homebrew

### ISSUE THREAD

**Issue by pvinis** [dexterleng/vimac#123]
I added it to my tap for now, so anyone can install using `brew cask install pvinis/pvinis/vimac`.

For a more "official" thing, you can make a repo called `homebrew-something`, make a dir called `Casks`, and in there make a file called `vimac.rb`. In that file put what I have https://github.com/pvinis/homebrew-pvinis/blob/master/Casks/vimac.rb here.

Then anyone can install it using `brew cask install dexterleng/something/vimac`.

Replace `something` with something more meaningful I guess :p

**Comment by dexterleng** [comment]
@pvinis closing this as #152 seems to have more engagement.

**Comment by rjcoelho** [comment]
@dexterleng 0.3.6 was the last binary release on github. Using appcenter doesn't play nice with brew cask. Can you please keep uploading the releases also to github ? thanks
