### ISSUE TITLE
automate accessibility permission request  maybe possible

### ISSUE THREAD

**Issue by andrewvmail** [dexterleng/vimac#124]
coming in from https://github.com/dexterleng/vimac-releases/issues/43
maybe its possible with this 
```
git  clone git@github.com:jacobsalmela/tccutil.git
cd tccutil
sudo ./tccutil.py --list  | grep dexter
```
I see few entries of your app

**Comment by dexterleng** [comment]
I've tried to modify the database before,  but it didn't work probably because of SIP in Mojave.

**Comment by dexterleng** [comment]
Currently for development I'm using an AppleScript to grant the permissions, which I think is too fragile to be run in release mode.

https://github.com/dexterleng/vimac/blob/master/grant-accessibility-permission-dev.scpt

**Comment by andrewvmail** [comment]
ah yeah  i thought you might  have  tried that,  and yeah that  python script specifically  mentioned it wont work with SIP on
