### ISSUE TITLE
Alerts not mapping

### ISSUE THREAD

**Issue by orthodoX** [dexterleng/vimac#126]
It seemed natural to me to just dismiss an alert with Vimac, but then I realised, oops:

<img width="399" alt="Screenshot 2020-03-11 at 10 43 18" src="https://user-images.githubusercontent.com/370935/76409879-51ad3380-638f-11ea-98c2-7875f236fde4.png">

@dexterleng Is it possible to map the alerts, since they are persistent on the screen?

**Comment by dexterleng** [comment]
Noted. I'll look into it. I found it rather  annoying too.

**Comment by dexterleng** [comment]
Look forward to it in the next update :)
