### ISSUE TITLE
Right mouse click emulation

### ISSUE THREAD

**Issue by orthodoX** [dexterleng/vimac#127]
I noticed that for `ToothFairy` menubar item for example, has bound actions to both left and right click. On the left click it connects to the device and on right click it's shows the dialog with status and preferences:

<img width="283" alt="Screenshot 2020-03-11 at 12 00 19" src="https://user-images.githubusercontent.com/370935/76410567-69d18280-6390-11ea-846f-9a474f4c221a.png">

@dexterleng Did you consider maybe of adding a right mouse click emulation as a feature?

**Comment by dexterleng** [comment]
It's already there ;)

https://vimacapp.com/how-to-use/

I will have to make the link more accessible.

**Comment by orthodoX** [comment]
Oh, right, great! 👍🏻
I'll make a PR to add this info to the readme, since some people (including myself I guess) will more check the repo's readme here, rather than info on the website 😄
