### ISSUE TITLE
Customizable navigation keys

### ISSUE THREAD

**Issue by BackOrder** [dexterleng/vimac#133]
Dvorak typist here. It would be nice to be able to customize navigation keys. HJKL isn't exactly friendly on a Dvorak keyboard.

**Comment by BackOrder** [comment]
I filled this issue using vimac. :)

This is a reference to an earlier conversation on Reddit. [See here.](https://www.reddit.com/r/macapps/comments/fmbw9u/vimac_navigate_macos_with_just_the_keyboard/)

**Comment by dexterleng** [comment]
Addressed in #137. Look forward to it next update! Let me know if there are bugs/issues/possible improvements.

**Comment by BackOrder** [comment]
Hiya! Customizing hint characters is different from customizing navigation keys. For example, on my keyboard, **HJKL** is **DHTN**. So it would make sense for me to change the keys for something more comfortable.

**Comment by dexterleng** [comment]
@BackOrder my bad 😬.

**Comment by BackOrder** [comment]
No worries! Vimac is otherwise great. I'm looking forward the feature. :grinning:

**Comment by dexterleng** [comment]
@BackOrder scroll keys have been customizable for some time now, closing this issue.
