### ISSUE TITLE
Can we blocklist certain apps? I like ctrl+space, but don't need it in VS Code

### ISSUE THREAD

**Issue by chriszrc** [dexterleng/vimac#145]
Title says it all. I also vimuim in chrome, and it's very useful, but there are certain sites that have their own keyboard shortcuts built-in, so it's very handy to be able to block list them. I'd like to have the same functionality with vimac.

**Comment by RobinHoutevelts** [comment]
I'm surprised this is'nt already in the product

**Comment by dexterleng** [comment]
There are several similar feature requests. Closing this in favor of #139
