### ISSUE TITLE
vim-like text input fields possible?

### ISSUE THREAD

**Issue by normen** [dexterleng/vimac#166]
I was wondering if it was possible to add a simple vim-like text edit mode with insert and normal mode for system-wide text fields. So that you could basically use vim movements in any text field. I am already using an [edit in vim](https://github.com/normen/vim-macos-scripts) automator action to edit long text but for simple text input fields (e.g. iMessage) having the basic movement and edit keys would be very nice.

Something akin to the [vimode.py](https://github.com/GermainZ/weechat-vimode) script for the weechat IRC client would suffice imo, it simulates most basic editing commands you'd use in a single line which really isn't as complicated as it sounds (or a whole VIM emulation would be).

So the question goes to you having the experience with the MacOS accessibility options - do you think this would be possible/feasible? If you have some pointers but no time to look at an implementation - I have some limited experience with MacOS / Swift development so I could take a stab.

**Comment by dbalatero** [comment]
I have this working at the moment, but there is more work to be done on it, particularly around rich text fields!

https://github.com/dbalatero/VimMode.spoon

@dexterleng I don't know if you ever want to chat in general, but I have a long term goal of making a well working, system-wide Vim mode. I am currently experimenting with Neovim's RPC to actually proxy to a real Vim instance in the background.

**Comment by grossjohann** [comment]
Actually, vi-like navigation would be useful for other UI elements, as well, not just for text fields.  For example, I would love to be able to navigate the menu bar with hjkl.  Or the files and folders in Finder.

**Comment by dexterleng** [comment]
@dbalatero This is really cool! 

> I am currently experimenting with Neovim's RPC to actually proxy to a real Vim instance in the background.

This sounds really interesting. I'd like to know more and potentially get involved.

**Comment by dexterleng** [comment]
I think this is out of the scope of what Vimac should support.
