### ISSUE TITLE
Error: "“Vimac 2” can’t be opened because Apple cannot check it for malicious software."

### ISSUE THREAD

**Issue by ym-han** [dexterleng/vimac#167]
Hi,

I'm getting the following error after downloading the latest version of vimac from the wesite and trying to open it: “Vimac 2” can’t be opened because Apple cannot check it for malicious software. The software needs to be updated.

Any help would be appreciated! Thanks in advance!

**Comment by dexterleng** [comment]
Hi

You have to RIght click -> Open :/
I'm working on getting Vimac notarized so this doesn't happen.

Dexter

**Comment by ym-han** [comment]
Thanks, that works! :)

**Comment by muyinliu** [comment]
> Thanks, that works! :)

Please close this issue since it's already solved.
