### ISSUE TITLE
Minimal functionality on chrome tools

### ISSUE THREAD

**Issue by thielium** [dexterleng/vimac#169]
When I try to use vimac on chrome dev tools, I get weird results.

**Version**: 0.3.10
**OS X version**: 10.15.5 (19F101)
**Desired Behavior**: Tabs and other interactive objects have hint associated with them.
**Actual behavior**: Minimal hints; lots of to tabbing.

See the attached screenshot. I've had it work maybe one time very effectively on chrome tools before, but I can't figure out why it would do it in one case not the other.

![Screen Shot 2020-07-09 at 9 37 03 AM](https://user-images.githubusercontent.com/37806340/87047031-ef8efe80-c1c7-11ea-86dd-d9f65fc7b1b2.png)

**Comment by thielium** [comment]
(Extremely useful piece of software, by the way, thank you for developing it.)

**Comment by dexterleng** [comment]
Refer to #78.

**Comment by thielium** [comment]
Thanks!
