### ISSUE TITLE
Long lag (5+ seconds) before hints show up on latest upgrade?

### ISSUE THREAD

**Issue by mmroczka** [dexterleng/vimac#170]
Thanks for such an awesome piece of software (do you have a donation page anywhere? I'd love to donate to the project to keep it going!).

On the latest upgrade of Vimac I've noticed a _huge_ slowdown in when the links show up. I am really not sure what's causing it. :( Since the links take 5+ seconds to show up, it's now almost always faster to just use a mouse to click on things. Any way we can speed up the link hints or are there things I can do on my end to speed them up? It's not the hardware, I've got a pretty great Macbook Pro.

<img width="250" alt="About This Mac 2020-07-12 12-48-58" src="https://user-images.githubusercontent.com/13666593/87253113-2bcb9480-c43e-11ea-9072-231153a825a7.png">

Is there a cache I need to flush or anything else I can do to speed this up again?

**Comment by dexterleng** [comment]
I've not experienced this. From my experience, Vimacs performance can be heavily affected by CPU usage. Have you tried restarting your macbook?

**Comment by mmroczka** [comment]
I restart it daily. I'll admit that I have a lot running on my mac on a typical day, but it's no more than it has been since I first started using Vimac months ago. Is there anything I can do to speed it up? Maybe just increase its priority in `renice`?

**Comment by p10q** [comment]
Just want to say I love vimac! And have been using it for the past few days now.. and am so thankful.

That said, with apps that have hundreds of hints (three letters) etc. it takes at least 1-2 seconds. Any performance optimization that could be done here would be super appreciated. I have half a mind to explore/profile a bit this weekend in case it helps too. Maybe some critical path loops can be super optimized.

**Comment by dexterleng** [comment]
@p10q if you monitor Vimac in activity monitor, it uses spikes to ~ 10% CPU usage (at least for me) each time hint mode is activated. I think activating hint mode on a schedule is going to take a hit on battery life, although I have not done measurements.

I have an idea to improve the performance, which is to maintain an element tree that mirrors the actual UI element tree. This means we only have to query once and attach notifications that manipulate that tree.

The accessibility API allows you to attach notifications to UIElements [1] to listen for destroy, moved, created events which I think could be used to implement the mirroring element tree idea

[1] https://github.com/tmandry/AXSwift/blob/f2cbfeb7fe770438c30654d80a109b51b8d6fbbb/Sources/Constants.swift

**Comment by p10q** [comment]
That's really interesting. Thanks for the info! I'm not sure when I'll have a chance to hack on this, but that's exciting that you have various approaches you're thinking about. I'll have to give it a shot when I have a little more time.

(Another thing that might be fun to pursue is doing some sort of OCR / scan of raw pixels / framebuffers to generate hints? I feel like that'd take care of apps that haven't properly implemented accessibility identifiers. Might really help visually impaired folks too. It'd be awesome to have Vimac + this sort of "scan pixels for landmarks / differences in pixels" as a backup. Anyway, I feel like that might be interestingly performant, but of course the algorithm for differentiating what to hint would be quite challenging - but I think possible to do well. XEasyMotion is nice but just not quite fast enough for frequent use. But yeah.. having different "levels" of landmark detection. E.g., I mind ctrl-f to trigger hint mode for ViMac. Having like ctrl-f ctrl-f trigger a more detailed / exhaustive listing of hints. Whereas ctrl-f would only trigger a first pass of hints. Maybe something to consider long-term.. ctrl-f ctrl-f ctrl-f could paint the whole screen with hints more or so.)

**Comment by albert-ying** [comment]
It is an amazing tool, thank you! However I also experienced the lag as described, it varies from 2 to 10 sec. It would be nice if you can optimize it. Or as p10q suggested, if this lag is due to too many "buttons" to mark, maybe prioritize them and show something first instead of just lagging.

**Comment by dexterleng** [comment]
@albert-ying @mmroczka @p10q 

I have released a new version of Vimac (0.3.11) that improves performance especially in webkit/electron apps. Let me know if you still face this!

**Comment by p10q** [comment]
Whoa, super impressive. Slack and other webkit/electron apps work really well now. Thank you! 

(Did you know this works for the iOS simulator too, which is super awesome for simple automation. Anyway, thanks again!)

**Comment by mmroczka** [comment]
This is awesome! This can probably be closed since it seems to fix my issue at least. :)

**Comment by albert-ying** [comment]
@mmroczka @p10q @dexterleng 

Hi, did you change the setting of "Shown of Action"? Cuz from my side, although it is faster, but still around 3-sec lag (varies for different apps).
Dexter, will you recommend me to uncheck some "Shown of Action" choices to get better performance? Which would you suggest to uncheck /preserve ?

**Comment by mmroczka** [comment]
Where is that even located? I see nothing with that title
![image](https://user-images.githubusercontent.com/13666593/91669195-c78d8e80-ead8-11ea-84c5-1f84d5315bbf.png)

**Comment by albert-ying** [comment]
Hmm weird.. did you update it?
![image](https://user-images.githubusercontent.com/59846322/91669253-7b931780-eae1-11ea-980c-f5be9b76ba91.png)

**Comment by mmroczka** [comment]
I had thought so. :/ it even works better or so I thought... Ok, i just updated it. I'd also like to echo @albert-ying 's question on the general performance impacts on each of these. I don't know what any of them are. 😅

**Comment by dexterleng** [comment]
@albert-ying 

> Dexter, will you recommend me to uncheck some "Shown of Action" choices to get better performance? Which would you suggest to uncheck /preserve ?

You should not see much (or any) performance improvements. I would recommend uncheck `AXShowMenu` (see https://github.com/dexterleng/vimac/issues/172#issuecomment-678773515)

**Comment by dexterleng** [comment]
I'll close this for now. Please reopen if you see fit!
