### ISSUE TITLE
Hints only appearing on main monitor

### ISSUE THREAD

**Issue by phamousq** [dexterleng/vimac#174]
Toggling the hint mode while the cursor and focus are on a secondary monitor only show hints on the main monitor. Currently on a hackintosh on Catalina 10.15.6. Thanks for your work on this tool!

**Comment by dexterleng** [comment]
@phamousq could you elaborate on how I can replicate this? I have no issues with multi-display. It is intentional that hints are only shown for the active window.

**Comment by phamousq** [comment]
Thanks for getting back to me! The issue was not with Vimac but I believe with some MacOS settings. The issue was fixed when I selected this option from 'Mission Control' in settings:
![image](https://user-images.githubusercontent.com/57886809/89101392-0e4a7480-d3c5-11ea-858b-97d14049975e.png)

**Comment by max-sixty** [comment]
FWIW I have the same issue, and I had that option selected. If I can work out what's causing it, I'll post back here.

**Comment by blackketter** [comment]
I'm seeing this too.  The menubar is on an external monitor and the secondary display is the macbook's display.  I have the "When switching to an application, switch to a space with open windows for the application" box checked (FWIW: I don't use Spaces). 

Hints only appear on the external monitor, even when a window spans both monitors.

![Screen Shot 2020-09-03 at 10 06 14 AM](https://user-images.githubusercontent.com/131679/92145685-6feb6d80-edcd-11ea-8e99-47e0e3970707.png)

**Comment by kevincolyar** [comment]
Seeing the same issue here using two external monitors and hints only show up on the "main" external monitor.  Also have the Mission Control option checked.

**Comment by Sangdol** [comment]
I also had the "When switching to an application, switch to a space with open windows for the application" option selected but it didn't work on my second monitor.

In my case, it works when I've selected the "Display have separate Spaces" option. Given that the screenshot @phamousq shared has both of them selected, I assume it works when you select both.

**Comment by dexterleng** [comment]
@blackketter have you disabled the "Display have separate Spaces" option? Because I don't believe windows can span multiple windows like in you screenshot.

<img width="599" alt="Screenshot 2021-02-12 at 11 59 54 PM" src="https://user-images.githubusercontent.com/34204380/107791024-6871bc80-6d8e-11eb-948b-53b0b72aea25.png">

**Comment by dexterleng** [comment]
Just tested with **Displays have separate Spaces disabled**. Can confirm that hints are only shown for a single screen when a window spans multiple displays.

**Comment by blackketter** [comment]
These are my Mission Control settings, my displays do not have separate spaces:

![Screen Shot 2021-02-12 at 1 03 21 PM](https://user-images.githubusercontent.com/131679/107822344-cec8f180-6d32-11eb-9f91-5a07b1f44921.png)

**Comment by blackketter** [comment]
So, currently with these settings I can show hints in a window in either monitor, but when a window spans monitors the hints show on only one monitor.


Also, when a window is on the secondary (no menubar) monitor, the hints appear in the window, but not on the menubar.  
<img width="456" alt="Screen Shot 2021-02-12 at 1 14 06 PM" src="https://user-images.githubusercontent.com/131679/107823179-33d11700-6d34-11eb-8462-80af9b0f9b76.png">
@dexterlang: Should I open a separate issue about this?

**Comment by dexterleng** [comment]
I've updated the description of #309 to include this. Thanks.
