### ISSUE TITLE
v0.3.10 failed update

### ISSUE THREAD

**Issue by fanckush** [dexterleng/vimac#175]
I was looking forward to the v0.3.10 because of the font size feature but when I try to update the app I get:
<img width="420" alt="image" src="https://user-images.githubusercontent.com/6278713/88627857-4d1eb880-d0ad-11ea-9dcb-0de4e66e0960.png">

not sure if this is specific to me or if it's an issue with the app

**Comment by dexterleng** [comment]
@fanckush Ah tested to be broken :/. The sparkle XML files have been moved from `vimac-releases` to being hosted with AppCenter. I tried to make it a smooth transition but I guess this doesn't work. You will have to redownload 3.10.
