### ISSUE TITLE
Scrolling Does Not Work in IntelliJ IDEA editor panes.

### ISSUE THREAD

**Issue by stephanoparaskeva** [dexterleng/vimac#176]
Sometimes when I activate `scroll` in intelliJ it only detects the project tree, and does not let me scroll editor panes. E.g:

<img width="792" alt="Screenshot 2020-07-28 at 22 53 38" src="https://user-images.githubusercontent.com/40718272/88726198-3156f900-d125-11ea-80c3-f7e1bcd2c361.png">

**Comment by dexterleng** [comment]
@stephanoparaskeva I'm guessing the editor pane is not an actual `AXScrollArea` (you can use the Accessibility Inspector to check).

Currently for apps with zero scroll areas, the entire window acts as the scroll area in Scroll mode. I think a solution here would be to add the entire window as the last scroll area even if the app already has > 0 scroll areas.

**Comment by stephanoparaskeva** [comment]
> @stephanoparaskeva I'm guessing the editor pane is not an actual `AXScrollArea` (you can use the Accessibility Inspector to check).
> 
> Currently for apps with zero scroll areas, the entire window acts as the scroll area in Scroll mode. I think a solution here would be to add the entire window as the last scroll area even if the app already has > 0 scroll areas.

No on intellij the editor has its own scroll area. I know this because it sometimes works and sometimes does not.

**Comment by noorvir** [comment]
Any idea for a solution here or is it the case that the way IntelliJ does things is not compatible with vimac?

**Comment by dexterleng** [comment]
@stephanoparaskeva @noorvir 

Could you try enabling screen reader support for IDEA? I don't have it installed.

https://www.jetbrains.com/help/idea/accessibility.html#install_and_set_up

Non native apps typically don't report accessibility information by default so looking for enabling screen support is something you should look for first.

**Comment by dexterleng** [comment]
Please provide the requested information and re-open. Closing this for now.
