### ISSUE TITLE
`ctrl-space` not getting picked up when key events sent using Talon

### ISSUE THREAD

**Issue by ym-han** [dexterleng/vimac#177]
Hi Dexter,

Thanks once again for making this great app. I use a hands-free input program called Talon (https://talonvoice.com/) that basically allows me to do key presses (among many other things) with my voice. But for some reason, when I do`ctrl-space` (my vimac keybinding) with Talon, that doesn't getting picked up by Vimac. The _physical_ keyboard keypresses of `ctrl-space` do, however, get picked up. Would it be possible to get Vimac to be capable of listening to key events from Talon as well?

I haven't really had this kind of issue with any other app, so I'm not sure what the cause is. I'm guessing it's the way that Vimac is listening for keyevents, though I'm not sure.

Thanks once again for this awesome app!

**Comment by dexterleng** [comment]
Interesting. I'm using MASShortcut for shortcuts.

**Comment by ym-han** [comment]
Ah changing the modifiers helped. I'm guessing `ctrl-space` must have been taken by some other app. Thanks and sorry for not testing more!

**Comment by dexterleng** [comment]
Glad to see its working! Closing this issue.
