### ISSUE TITLE
Increase contrast in preference text backgrounds

### ISSUE THREAD

**Issue by OolonColoophid** [dexterleng/vimac#194]
Hi there

I like this app! Interesting idea. 

I think the background of the textfield in the preferences is too dark...

<img width="551" alt="Screenshot 2020-08-30 at 18 25 04" src="https://user-images.githubusercontent.com/18744451/91665548-4d680480-eaee-11ea-985e-fe98a8afd726.png">

Cheers

**Comment by OolonColoophid** [comment]
Hi Dexter

I'd be happy to have a crack at this and raise a PR - what do you think? I'm a novice Swift developer and I'm having some issues getting your code to build on 10.15 but I should get there in the end...

Cheers

Ian

**Comment by dexterleng** [comment]
Hi Ian, apologies for the incomplete build instructions (there should be a cocoapods and carthage installation step). I'll have to update it soon.

Go ahead raise a PR! I look forward to your contribution.

Let me know if you need help building or navigating the codebase.

**Comment by dexterleng** [comment]
@OolonColoophid 

I have updated the build instructions! Let me know if it doesn't work for you.

**Comment by blackketter** [comment]
I'm trying to get started building too.  Thanks for updating the instructions.  I did need to install carthage via homebrew, that should probably be mentioned.

I'm stuck with signing with the error: 
`No account for team "LQ2VH8VB84". (Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.)`
Not sure if this is your team, but I can't seem to find it to remove or update.

**Comment by OolonColoophid** [comment]
I fixed the signing error by substituting my own team there.

**Comment by blackketter** [comment]
Found it, thanks!

**Comment by OolonColoophid** [comment]
It builds!

The background for the text fields is used when calling this method:

`   func changeCustomTextViewBackgroundColor(textField: NSTextField, color: NSColor) {
        textField.backgroundColor = color
        
        // setting backgroundColor does not work properly after the first time until text field is out of focus.
        // see: https://stackoverflow.com/a/16489472/10390454
        textField.isEditable = false
        textField.isEditable = true
    }`

I'm not sure why the colour is customisable (i.e. I don't see what value this adds to the user experience). I would simply suggest using `NSColor.textBackgroundColor`, then removing the parameter from this method along with those who call it. What do you think?

We would be left with the following appearance:

<img width="622" alt="Screenshot 2020-09-04 at 18 57 14" src="https://user-images.githubusercontent.com/18744451/92272133-e6c55b00-eee0-11ea-94cc-13c03496659a.png">
<img width="622" alt="Screenshot 2020-09-04 at 18 57 00" src="https://user-images.githubusercontent.com/18744451/92272138-e7f68800-eee0-11ea-8b49-87996a289830.png">


Cheers
Ian
