### ISSUE TITLE
Toolbar items are not available to  Vimac

### ISSUE THREAD

**Issue by blackketter** [dexterleng/vimac#198]
I'd love for Vimac to be able to provide hints to click on items in a window's toolbar.  

Not sure if this is not available due to an OS limitation, I see that if I have a toolbar-based dropdown menu, I Vimac _does_ show a hint for that item and the menu items, and in some apps (for example Pages.app) some Toolbar items _are_ available from Vimac, but not all.  In that case, it appears that buttons that show dropdowns do appear.

Keep up the great work!

**Comment by dexterleng** [comment]
@blackketter Do you mind providing an example of a toolbar that Vimac doesn't show hints for?

**Comment by blackketter** [comment]
Upgrading to 3.11.1 fixed this for me.
