### ISSUE TITLE
Ctrl + Space is not a good choice for default hint key.

### ISSUE THREAD

**Issue by kingname** [dexterleng/vimac#201]
Most countries don't use english as their writing language,  for instance China,  there must be some `input software` which is used to change english letters to their languages. the `Ctrl + Space` is a global short cut for changing input software. If vimac  uses this hot key, the people in these countries even could not chat with others.

**Comment by grossjohann** [comment]
Also, the IDEs IntelliJ and Eclipse use Ctrl+space for code completion.
