### ISSUE TITLE
Feature idea: vi-like modal navigation (normal mode?) with mode indicator

### ISSUE THREAD

**Issue by grossjohann** [dexterleng/vimac#205]
This is related to #166.

It would be nice to be able to hit a key to toggle something similar to "normal mode" in vi.  While normal mode is active, we could show some indicator on screen, e.g. a border around the screen similar to how web conferencing software does it when you present your screen.

While normal mode is active, hjkl would be the same as the cursor keys, b and w could be like option-left and option-right, X could be like backspace, x could be like forward delete, and so on.  This would allow folks to navigate text entry fields (this is the aspect mentioned in #166) but also other UI elements, such as the menu bar, or context menus, or popup dialogs.

There is some other software I encountered that used the cmd key as a toggle: when you tap the cmd key, it toggles normal mode, but when you hold cmd and press it together with another key, it does the normal cmd modifier action.

Just a thought.

While normal mode is active, f could invoke hints mode (that seems to be what vimium and similar web browser extensions do).

**Comment by dbalatero** [comment]
As I mentioned on the other thread, this is something that I already have going here, complete with mode indicator (I am using it as I write this comment in Chrome!): https://github.com/dbalatero/VimMode.spoon

Either developing it further on its own to support more keys, or taking its code/ideas and merging it into here would be just fine with me. Proxying to Neovim RPC is another good option, but there are a ton of field edge cases, so you actually end up needing two modes: one for fields that fully support accessibility, and one for fields that don't (e.g. all Electron apps).

**Comment by grossjohann** [comment]
@dbalatero yes, VimMode.spoon looks really nice.  I now remember that I saw it some months ago and decided not to look more deeply because I wanted to use the cmd key as a toggle...  Maybe that was a silly restriction on my part.  Maybe I should try if jk or jj work well enough.

**Comment by dbalatero** [comment]
> I wanted to use the cmd key as a toggle

You can still do this. The problem is that command is a modifier, not a key press. The easiest way out is to set up a dual tap key with Karabiner (without figuring out how to listen only for modifier presses and setting a timeout delay to detect tap vs hold…).

Google for Karabiner dual tap key, and make your command key send some unused function key (like F20) when tapped, and act as command when held.

Then bind normal mode to F20 in Hammerspoon.

> Maybe I should try if jk or jj work well enough.

They work great, but if you choose one, you should do `jk` as it's faster to type.

Also to be clear this isn't an advertisement, I'm more interested whether @dexterleng has any interest in a more full experience in Vimac, and if so are you interested in collaborating? I've spent a couple years hunting down text entry edge cases here, and I can share the things I've learned.

**Comment by dexterleng** [comment]
@dbalatero I just tried it - its really impressive. I never thought the accessibility API could be reliably used to do this.

Yes, I would love to collaborate!

**Comment by dbalatero** [comment]
@dexterleng Awesome - would you mind emailing me? (you can find address at the footer of my site https://balatero.com)

**Comment by grossjohann** [comment]
I would like to update that I've "stolen" the idea of using Karabiner Elements for the toggling.  So what I have done now is this:

* Configure Karabiner Elements so that Cmd emits F20 when pressed alone, but continues to act as the Cmd modifier when used with other keys.  Getting this logic working in Hammerspoon was fiddly.
* Configure Hammerspoon so that F20 toggles "vi navigation" mode, and when "vi navigation" mode is active, then hjkl act like cursor keys and a few other things.  It is not a complete vi emulation at all, just a pretty superficial thing.

I briefly tried VimMode.spoon and it did not allow me to navigate the menu bar.  But @dbalatero says it should be working.  So I assume that I have done something wrong.  When I have some spare time, I'll have another go.  For sure, VimMode.spoon is much more spiffy than my basic solution!

**Comment by dexterleng** [comment]
jsadfasd
