### ISSUE TITLE
Feature - Dispatch to Vimium if using Chrome or Firefox

### ISSUE THREAD

**Issue by j-martin** [dexterleng/vimac#207]
It could be an option. If the user presses `ctrl-space` (or their non-default key binding) and Chrome is select it could dispatch a `f` (`Open a link in the current tab`) key event to Chrome to open a similar view. 

I guess I could implement that myself via Hammerspoon by sending different key events myself...

**Comment by egreenfield** [comment]
Just adding a +1 for this...I'm not sure I would integrate the full capabilities of vimium (i..e, all the navigation commands)...just would love clickable links and hotspots in the webpage to be actionable via vimac.  If vimac did that, I would probably just use vimac and not vimium (browsers already have pretty good navigation shortcuts built in).

**Comment by j-martin** [comment]
Alternatively, it could be a map of application to a key sequence defined by the user.

For example, for me it would be:
```
Emacs -> <spc>ss
Chrome -> f
```

As for @egreenfield suggestion, I would be shocked if vimac had any way to access the DOM in Chrome.

**Comment by dexterleng** [comment]
@j-martin it can, but it's disabled. Refer to #78

**Comment by j-martin** [comment]
@dexterleng it can dispatch the key even OR interact with the DOM?

**Comment by dexterleng** [comment]
@j-martin Both :)

**Comment by j-martin** [comment]
I'll close in favor of #78 then. Thanks for the clarification.
