### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by a-b** [dexterleng/vimac#210]
# Steps to reproduce
1. Go to the https://vimacapp.com/
1. Click `DOWNLOAD VIMAC` button
1. Get redirected to the https://install.appcenter.ms/users/dexterleng/apps/vimac/distribution_groups/sparkle with ```This site can’t be reached https://install.appcenter.ms/users/dexterleng/apps/vimac/distribution_groups/sparkle is unreachable.
ERR_ADDRESS_UNREACHABLE```

<img width="930" alt="Screen Shot 2020-09-01 at 11 11 19 AM" src="https://user-images.githubusercontent.com/585662/91890242-04c25f80-ec44-11ea-972a-f55765fdc8d3.png">

**Comment by dexterleng** [comment]
Seems to be up now for me. I'll reopen if this is persistent.
