### ISSUE TITLE
Custom character and text size fields in Hint Mode preferences have dark background color

### ISSUE THREAD

**Issue by blackketter** [dexterleng/vimac#216]
Not sure if this is by design, but it throw me off every time I open the preferences.  These fields should appear as normal text boxes, I think: 
<img width="441" alt="Screen Shot 2020-09-02 at 3 33 19 PM" src="https://user-images.githubusercontent.com/131679/92043898-e2a70b00-ed31-11ea-81af-d7bd76b3396f.png">

**Comment by dexterleng** [comment]
This is because validation in those fields failed (and hence Vimac uses the default configuration). If you entered a correct value it would become normal.

**Comment by blackketter** [comment]
From a usability standpoint, it looks kind of broken.  I suggest that you pre-fill the field with the default characters and display some warning text below if user changes it to invalid text.
