### ISSUE TITLE
cannot activate scroll mode if mouse is on clickable items

### ISSUE THREAD

**Issue by tshu-w** [dexterleng/vimac#218]
Hi, it seems like vimac cannot activate scroll mode if the mouse is on the clickable items in web page.

version: 0.3.11.1
browser: Safari  13.1.2
system: macOS 10.15.6

**Comment by blackketter** [comment]
It looks to me that this is true for anchors but not all clickable items (such as buttons or divs)

**Comment by tshu-w** [comment]
@blackketter aha, yes.

**Comment by dexterleng** [comment]
Any way specific site I can use to replicate this? Tried this on some buttons and anchors on github.com on Safari but they worked as expected.

**Comment by tshu-w** [comment]
try to move you mouse on `Pull Request` and have a try?
<img width="989" alt="Screen Shot 2020-09-05 at 8 02 54 PM" src="https://user-images.githubusercontent.com/13161779/92304694-cb2a8500-efb2-11ea-8af1-5ac8fc749324.png">

**Comment by blackketter** [comment]
I see the red outline flash quickly on the press of the "s" key, so it looks like the scroll mode is triggered but then cancelled.

**Comment by dexterleng** [comment]
Can't replicate this. I normally use CTRL-J but have tested with CTRL-S

**Comment by blackketter** [comment]
It happens for me when I have the shortcut set to CTRL-S, but not when I set it to CMD-OPTION-S.

**Comment by tshu-w** [comment]
my shortcut is cmd-opt-ctrl-j

**Comment by blackketter** [comment]
@tshu-w can you test to see if cmd-opt-j works?  I wonder if it's the ctrl key that is the issue.

**Comment by tshu-w** [comment]
@blackketter Yes, when I press cmd-j/k I got `Display a menu (for ...)`, which make scroll mode exit immediately.

**Comment by dexterleng** [comment]
Figured out that "Show Status Bar" option is what is breaking scroll mode in Safari.

![Screenshot 2020-09-06 at 1 26 49 PM](https://user-images.githubusercontent.com/34204380/92318848-a1ba3980-f044-11ea-8df3-8d3c8f5a05c8.png)

**Comment by dexterleng** [comment]
I have filed a report with the Safari team. I don't think I will fix this since this is due to a bug in their accessibility implementation.
