### ISSUE TITLE
AXChildren - really slow if there are many children

### ISSUE THREAD

**Issue by dexterleng** [dexterleng/vimac#221]
Vimac on the Mail app is REALLY slow because of it.

**Comment by blackketter** [comment]
I can confim this when viewing a very large inbox.  Smaller mail folders are responsive.

Similarly, Preview is very slow when viewing a PDF with many pages.

**Comment by blackketter** [comment]
Confirmed for both Mail and Preview.  A really great and important fix.

**Comment by blackketter** [comment]
Hm, hold up. Testing more...

Preview is definitely better for my 3000 page file (not instantaneous, but within a couple of seconds.)

Mail seems to be inconsistent for me now.  Can take many seconds for hints to appear.

**Comment by dexterleng** [comment]
@blackketter 

Interesting - Mail is way faster for me.

**Comment by blackketter** [comment]
I appears to be slow for me only when viewing a mailbox that has thousands of messages in it.  About 1 second for 1k messages, 4 seconds for 20k messages, 8 seconds for 100k, 21 seconds for 195k. 

It appears that when I first open a large mailbox it works quickly, then as Mail populates the mailbox it slows down.  Then it appears to get marginally faster in subsequent invocations.

This is on a 2019 13" MBP 2.4GHz quad-core i5 w 16GB RAM

**Comment by dexterleng** [comment]
@blackketter I have 9000 messages, and I've scrolled to the bottom to load all of them. The query time no longer should scale by no. of messages with the #222.

**Comment by blackketter** [comment]
Aha, somehow I was on the crash branch!  Not sure how that happened.  Sorry about that.

Mail is indeed faster on long mailboxes.  Yay!  <1 second in all cases I can see.

In Preview, a 111 page pdf is similarly fast.  A 3000 page PDF is 3 seconds or so.

**Comment by dexterleng** [comment]
@blackketter Thats good hear! The main change made in #222 optimized for AXTables and AXOutlines which are not used by Preview (which still scales by no. of AXPages). That PR inadvertently reduced some AXChildren calls so that may result in slightly faster performance for preview.
