### ISSUE TITLE
Show hints for AXRows if they do not have children that are hintable

### ISSUE THREAD

**Issue by dexterleng** [dexterleng/vimac#223]
Frequently there are rows whose children elements that don't have actions, but should. e.g. Mail, Xcode:

![Screenshot 2020-09-05 at 10 04 47 PM](https://user-images.githubusercontent.com/34204380/92306703-d1752d00-efc3-11ea-9a73-92422720efab.png)

![Screenshot 2020-09-05 at 10 03 19 PM](https://user-images.githubusercontent.com/34204380/92306686-9d9a0780-efc3-11ea-9fa5-1f0fd5508dbb.png)

**Comment by FANYD** [comment]
Version 0.3.10 can show these hints

**Comment by dexterleng** [comment]
@FANYD yeah, slight difference being 0.3.10 also shows hints for AXRows when it's children are hintable
