### ISSUE TITLE
Move from User Preferences to JSON stored in ~/.config/vimac/

### ISSUE THREAD

**Issue by dexterleng** [dexterleng/vimac#230]
Similar to Karabiner Elements.

Doing UI work for the preferences is a PITA. It will be much easier to support some configurations (especially key binding related ones). Makes it easier to backup configuration files.

**Comment by Phrohdoh** [comment]
Please consider a `VIMAC_CONFIG_FILE` env var to allow custom file paths.

**Comment by narkkil** [comment]
I could help with this a bit if still needed.

I had a look at what the implementation would mean. I see two things:

1) Preferences stored in `UserPreferences.swift` can be changed quite straightforwardly, by creating additional `PreferenceProperty` structs and some configuration code (e.g. `UserConfig` class having similar methods to `UserDefaults`).
2) Key bindings and other `MASShortcut` dependents require some extra thought. I was thinking of storing them similarly to how VSCode does it in the format `Cmd + S` for example. This would make editing the file simple provided there was a mapping somewhere that could be used. However, looking at the `MASShorcut` `keyCode` and `modifierFlags` I don't see an obvious way to provide a mapping that is both readable to Vimac/`MASShortcut` and intuitively user-editable directly from the config file. Furthermore the signature `MASShortcut.init(keyCode: Int, modifierFlags: NSEvent.ModifierFlags)` hints that it would have to be in this format to work. If such a mapping doesn't exist it would require custom mapping code which would seem difficult to get right, or either limit it to very narrow combinations. An alternative is to ignore the editability in this case and have the raw integers in the configuration and handle errors somehow -- not great, but would allow portability of Vimac configs until it could be resolved somehow.

What do you think?

**Comment by dexterleng** [comment]
@narkkil Thanks for taking a look at how the implementation can be done. I've given thought to how it could be done some months/ I think the UI is something that I would like to keep since it helps with discoverability of newly added features/configurations. Previously, the UI work was really annoying because I was using storyboards, but I've solved that problem by programmatically building the views. Hence, I didn't see the need to spend time working on this.

Config file support in addition to UI configuration would add additional complexity for IMO not that much benefit. Would you mind sharing why this is something of interest to you?

**Comment by narkkil** [comment]
Sorry for the delayed response and thanks for elaborating on your initial reason for the issue!

Why this was of particular interest to me was to make configurations portable to other machines, which I often found myself doing. However in Vimac's case I feel the feature set is not large enough for this to be a significant nuisance. Since of this discussion I tend to agree it's perhaps not particularly useful for the cost of new development required.

**Comment by dexterleng** [comment]
Hey @narkkil! Thanks for sharing the potential issue, I'll keep this in mind if the Vimac configuration grows beyond a certain size. I try to keep the config thin and only add configs when enough users request/complain.

**Comment by lougreenwood** [comment]
@narkkil I have the same needs, but what I found to be acceptable for me is to extract my preferences into a set of `defaults write com.dexterlang.vimac bla -type bool true` commands and run them as part of my setup script. Maybe that could work for you?

**Comment by blackketter** [comment]
> You can use `defaults read com.dexterlang.vimac` to read the current config

it's actually: `defaults read dexterleng.vimac`

**Comment by narkkil** [comment]
Right, those work for me! Thanks @lougreenwood & @blackketter

**Comment by molleweide** [comment]
Could one of you guys please share your setup scripts for vimac? I am not sure how to do this. I would also like my custom keybindings to be setup via my dotfiles.
