### ISSUE TITLE
Hints display much slower in 0.3.12

### ISSUE THREAD

**Issue by blackketter** [dexterleng/vimac#236]
Hints take 10 seconds or more to appear in 0.3.12.  The cursor is hidden successfully immediately but hints take a long time to show up, no matter what AX actions I disable in the preferences.  This happens in all apps I tried (safari, mail, finder, system preferences, bbedit, etc.)

Scroll mode works fine, appearing immediately.

Any logging I can do or provide to help track this down?

**Comment by dexterleng** [comment]
@blackketter hmm i got another report on this. I've tested on my other machine and am not facing this issue.

Very strange, I'm not very sure how I can figure this one out.

**Comment by dexterleng** [comment]
Since are able to build Vimac, could you do a `git blame` to find the commit that is causing this issue?

**Comment by blackketter** [comment]
Is there any logging that has useful time stamps? Would be good to narrow down what's happening in the 10 seconds between when the cursor disappears and the hints appear.

**Comment by dexterleng** [comment]
@blackketter nope, no logging happens during hint activation.

**Comment by dexterleng** [comment]
Btw, AX actions does not effect performance, its a simple array filter.

**Comment by blackketter** [comment]
I'll try to narrow it down, but it's stopped happening!  Not sure what changed since my report, I haven't rebooted my machine or since then.  I'll start debugging when it happens again, first with sampling the process, then trying to narrow down the code change.

**Comment by dexterleng** [comment]
My guess is that you had two vimac instances running, or really high cpu usage.

**Comment by blackketter** [comment]
Can't reproduce.  May have had two instances running.  Will reopen if it happens again.
