### ISSUE TITLE
Cursor disappears and doesn't reappear if you switch apps while in hide mode

### ISSUE THREAD

**Issue by blackketter** [dexterleng/vimac#240]
Steps to reproduce:
1. Bring up hide mode with hotkey
2.Command-tab to another app
3.Hints disappear, but the mouse does not.

If you happen to move the mouse to a spot where it should change shape it will reappear.

Vimac: 0.3.12

**Comment by dexterleng** [comment]
I noticed this happening without activating hint mode - just alt tabbing.

**Comment by dexterleng** [comment]
strange - i could replicate this by alt-tabbing more than once while in scroll mode. alt-tabbing just once seems to show the cursor just fine.

**Comment by dexterleng** [comment]
Fixed in v0.3.13. Please reopen if you still face this issue
