### ISSUE TITLE
Store preferences in dotfile

### ISSUE THREAD

**Issue by tomoakley** [dexterleng/vimac#242]
Would it be possible to store the preferences in a dotfile, e.g `~/.vimac`? Along with hosting on homebrew (#152) this would enable vimac to be installed and configured on a new mac through dotfiles and an install script.

Apologies if this is a duplicate.

**Comment by molleweide** [comment]
+1

**Comment by dexterleng** [comment]
This is pretty high priority. I'll close this in favor of #230.

**Comment by tshu-w** [comment]
You can use [mackup](https://github.com/lra/mackup) or others tool to backup `Library/Preferences/dexterleng.vimac.plist`
