### ISSUE TITLE
Preferences have a black box over them

### ISSUE THREAD

**Issue by dbalatero** [dexterleng/vimac#244]
When I try to edit preferences in Vimac like "Custom Characters", there is a black box covering them up.

![image](https://user-images.githubusercontent.com/59429/93635013-898cd780-f9bf-11ea-9211-70cca572cb76.png)

The only way I can see them for editing is if I highlight the entire row:

![image](https://user-images.githubusercontent.com/59429/93635064-a45f4c00-f9bf-11ea-9100-d39b097c1097.png)

**Comment by dexterleng** [comment]
Looks like its caused by Light mode making the text color black

**Comment by blackketter** [comment]
I really find the custom colors in these text boxes unsettling.  I think the system defaults are probably best.

If you need to provide feedback about the field being set right, it's probably better to update the text near it.

**Comment by dbalatero** [comment]
@dexterleng can the custom colors be dropped and the defaults used instead so it works in light mode?

**Comment by dexterleng** [comment]
@dbalatero yeah, I look through the human interface guidelines to see how error states are represented
