### ISSUE TITLE
Not working with latest Chromium based browsers (but works in Safari).

### ISSUE THREAD

**Issue by eugeneware** [dexterleng/vimac#247]
I'm not getting the highlights showing inside the body of the latest Brave and Chrome browsers. It works in Safari though.

Is this a known issue.

A few weeks ago it was working great in Chrome. Were there any recent changes that would have caused this? I've rolled back to the last 5 versions of vimac and they all seem to have the same problem. Could it be a recent chrome engine issue or a macos update version?

For reference I'm running:

Brave: 1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit)
Chrome: 85.0.4183.121 (Official Build) (64-bit)
Safari: Version 14.0 (15610.1.28.1.9, 15610)
macos: 10.15.6 (19G2021)

**Comment by dexterleng** [comment]
Chromium support has been disabled for a year. Refer to #78 for why. Not sure why it was working for you in Chrome. Perhaps you were using something like VimMode.spoon?

**Comment by eugeneware** [comment]
@dexterleng I think I must have installed an earlier version or something . I think I originally had 0.3.11. But don't know why it was working. Because it definitely was for a week or two. I'm not using vimmode.spoon - but am using Magnet 2.4.7 is probably the closest to other bindings (apart from vimium - which I wasn't using for that particular screenshot). 

Thanks for creating such an amazing tool. I hope there's a workaround or that the chromium team fixes the underlying issue soon.
