### ISSUE TITLE
Option to not revert cursor position in Hint mode

### ISSUE THREAD

**Issue by kiding** [dexterleng/vimac#251]
v0.3.12 doesn’t permanently move the mouse cursor to the target position anymore, but only temporarily. An unfortunate outcome to this change is now hover events are not triggered—To be precise they are, but for a very brief period of time. I wonder if this behavior can be controlled via an option.

**Comment by nemosmithasf** [comment]
Rather than forcing the user the choose between moving vs not-moving via options, it might be better to have a prefix that indicates "move" vs "action". This is since a user will likely want both types of behaviour available at the same time.

eg `Mabc' = move, "abc" = action

**Comment by blackketter** [comment]
> Rather than forcing the user the choose between moving vs not-moving via options, it might be better to have a prefix that indicates "move" vs "action". This is since a user will likely want both types of behaviour available at the same time.
> 
> eg `Mabc' = move, "abc" = action

I like this approach.  It could also be used to set modifier keys when clicking (i.e. for option-click, "oabc")

**Comment by dexterleng** [comment]
@kiding and others -  May I ask, whats the use case for being able to move the cursor but not perform an action? It would be great if you could point to specific applications where you would like to perform a move.

**Comment by kiding** [comment]
I'm sure there are many other cases, but the apparent one I can think of is any website solely relying on a "hover" event to expose its submenus; for example: https://www.dhl.com, https://www.aliexpress.com, https://www.nytimes.com, and so on.

![Mar-04-2021 21-50-07](https://user-images.githubusercontent.com/1336881/109966449-9fa31000-7d33-11eb-9b17-dd44a36c4c29.gif)

**Comment by dexterleng** [comment]
Ah ok.

I'll experiment with the idea @nemosmithasf and @blackketter gave.

**Comment by blackketter** [comment]
Here's a related situation, where triggering an action to pull down a menu pulls down another menu.  I think that this specific case happens if the mouse jiggles a little bit: 
![ezgif-1-85ecd4ba1af5](https://user-images.githubusercontent.com/131679/112029376-6968dd00-8af6-11eb-91de-bf5fa6aed6a6.gif)
I'm not sure I understand why the mouse isn't moved to the location of the click from the hint.

**Comment by dexterleng** [comment]
@blackketter  does this happen frequently across all apps or is it just Mail?

**Comment by blackketter** [comment]
I can reproduce it in any app if I put the cursor on a menu item at the very top of the screen and trigger the hint for a different menu.  Doesn't happen every time, but quite often.  (I don't think it's the mouse jiggling, as I suggested before, as it happens when no mouse is connected and my hand isn't near the trackpad.)

https://user-images.githubusercontent.com/131679/112168189-50236780-8bae-11eb-8c96-20885992b8d4.mov

**Comment by dexterleng** [comment]
@blackketter I can't seem replicate this issue, but it should be because of the revert mouse cursor.

I think I'll remove the revert cursor feature since I don't really the benefit of having it there anyway, and it also causes the problems mentioned by @kiding and @blackketter.

**Comment by dexterleng** [comment]
I don't think this will solve the context menu issue @kiding mentioned, since performing a click on the menu will lead to a redirect to another page, when the intention is to hover over to show the submenus.

The new workflow should support a move command.

**Comment by kiding** [comment]
I should've come up with a better example, sorry about that! 

One case #360 would definitely solve is where only hovering does something while clicking is a no-op. Something like this:

![Mar-25-2021 18-05-00](https://user-images.githubusercontent.com/1336881/112447503-bbc72980-8d94-11eb-8851-f1fe60a2203b.gif)

I remember there are some implementations where clicking on it would present a popover, then the popover would be closed when the cursor is moved somewhere else, since it triggered a different hover event.

If there was a "move only" command, that would definitely solve most of the hover-related cases. But I expect #360 would also solve at least some of them—where the implementation assumes a cursor would not move after a click.

**Comment by dexterleng** [comment]
Added the ability to move the cursor if `Option` is held and removed cursor reverting. Its not the most ergonomic solution, but it works for now until the workflow is revamped.
