### ISSUE TITLE
ctrl - space sometimes working and sometimes not working

### ISSUE THREAD

**Issue by EhsanSarshar** [dexterleng/vimac#259]
macos: mojave 10.14.6
vimmac: 0.3.9
keyboard: external

**Comment by rbugajewski** [comment]
@EhsanSarshar Can you please verify if this only happens after boot (see https://github.com/dexterleng/vimac/issues/88#issuecomment-728872854) and close this issue if it is a duplicate?

**Comment by molleweide** [comment]
I might be experiencing similar

**Comment by dexterleng** [comment]
There is not enough information here for me to look into. Closing this.

It could be addressed in the latest version (v0.3.13) (see #255). Do let me know or reopen if you still face this issue.
