### ISSUE TITLE
Feature Request: ignore vimac when certain apps are active

### ISSUE THREAD

**Issue by JasonMFry** [dexterleng/vimac#263]
I like ctrl+space as the shortcut but it conflicts with my IDE. No matter what shortcut I use I'm likely to conflict with keybindings in a particular app, and I may not want to change either the keybinding in the app nor vimac's shortcut. If vimac could not activate hint mode when a certain app is active, that'd be nice!

**Comment by dexterleng** [comment]
There are several similar feature requests. Closing this in favor of #139
