### ISSUE TITLE
Hints stop showing 

### ISSUE THREAD

**Issue by geeogi** [dexterleng/vimac#266]
Thank you very much for creating Vimac - it works very well for me for the most part.

I am encountering a problem where the hints stop showing after Vimac has been running for some time (10-15 mins). When I press the keyboard shortcut the hints will show momentarily but will disappear as soon as I lift the keys, which gives me no chance to select a hint. Normally the hints continue to show until I select a hint or press the keyboard shortcut a second time.

Sometimes the problem goes away after a few minutes, but usually I need to quit and restart Vimac to get it working again. How can I solve this problem? Or how can I debug the problem?

I am using a custom keyboard shortcut (cmd-ctrl-shift-1) and custom hint characters (123456789).

**Comment by zhigang1992** [comment]
It's happening to me as well, but only in Safari. reload the page will work sometimes.

Are you experiencing it in other apps as well?

**Comment by zhigang1992** [comment]
I just realized that it won't work until I've moved the mouse a bit.

**Comment by geeogi** [comment]
yes, now that I think about it, it only happens in safari. And yes, just tried it, if I move the mouse then the hints seem to come back..!

**Comment by dexterleng** [comment]
Sounds like #218. A quick fix now is to disable "Show Status Bar".

**Comment by zhigang1992** [comment]
Nice, it seems that this fixed it for me. 

It was happening for both hint and scrolls, as soon as I let go of the ctrl key it disappears.

both the scroll red box and the hints

**Comment by dexterleng** [comment]
Awesome! Closing since its a duplicate.
