### ISSUE TITLE
Doesn't work in Notion 😢

### ISSUE THREAD

**Issue by sheltered-castle** [dexterleng/vimac#267]
As you can see from the screenshot below, there is no way of accessing any of the elements inside of Notion. It's a super popular app and where most of my todolist/calendar/documentation lives. Any chance we can get support for it? Right now all I have access to is the main menu.

![image](https://user-images.githubusercontent.com/61962883/98449404-f5a2d680-20f8-11eb-9673-0ebf4c4f30b0.png)

**Comment by zhigang1992** [comment]
I don't anything build with Chrome's web would work, I think this only works for native app with native control.

**Comment by dexterleng** [comment]
Using Accessibility Inspector to check the accessibility-ness of Notion. Looks like this is the lowest I can drill down to from traversing the UI Tree. I can't seem to access the buttons, so hints are not shown for them.

Its a Notion accessibility issue. Electron apps (e.g. vscode) generally work.

![Screenshot 2020-11-15 at 11 26 55 PM](https://user-images.githubusercontent.com/34204380/99189031-0fe45080-279a-11eb-860a-2a3c146725a1.png)

**Comment by dexterleng** [comment]
@zhigang1992 

Electron Apps work. Chromium doesn't. See #78.

**Comment by dexterleng** [comment]
Closing this now since theres nothing I can do about it. Consider reporting to the Notion team about its lack of accessibility!

**Comment by dexterleng** [comment]
<img width="1203" alt="Screenshot 2020-12-06 at 1 12 06 PM" src="https://user-images.githubusercontent.com/34204380/101272155-a5389a80-37c4-11eb-878c-eef61460b391.png">

Interesting. It works for me now. Maybe its an update.

**Comment by zhigang1992** [comment]
I think they just updated their Electron version.
