### ISSUE TITLE
Vimac doesn't work after launch until a "window focus" event has been fired.

### ISSUE THREAD

**Issue by dexterleng** [dexterleng/vimac#277]
So if had an application open, then you open Vimac. Vimac won't work until you switch active windows.

**Comment by blackketter** [comment]
Aha, that explains the behavior I've been seeing.  

Would it be possible for Vimac to trigger an application or window switch (and possible switch back) to force a widow focus event to be generated?  Maybe by opening a splash screen window and closing it?

**Comment by dexterleng** [comment]
A better solution is just to query for the active window when the shortcut is hit
