### ISSUE TITLE
Hints do not appear on a secondary monitor if application is in fullscreen mode

### ISSUE THREAD

**Issue by meucaa** [dexterleng/vimac#282]
**Vimac version**: 0.3.13
**MacOS version**: macOS Big Sur 11.1

For context, I am using three monitors with my laptop below two external monitors:
![monitors-layout](https://user-images.githubusercontent.com/16673538/103665253-810edb80-4f73-11eb-93f4-0672e4cf4af7.png)

When I focus on my upper-right monitor in a fullscreen application (IntelliJ here) and press Option+Space to toggle hints, I can see no hints on the upper-right monitor but a bunch of hints in the upper-left corner of my laptop monitor.

Here is the upper-left corner of my laptop monitor:
<img width="49" alt="laptop-screen-upper-corner-when-hinting-on-external-monitor" src="https://user-images.githubusercontent.com/16673538/103665266-84a26280-4f73-11eb-8db1-9a03416eab87.png">

Here is my upper-right monitor while the hints are being wrongly shown on my laptop monitor (you can see no hints):
![external-monitor-screen-when-hinting-in-fullscreen](https://user-images.githubusercontent.com/16673538/103665255-81a77200-4f73-11eb-94f1-fe6f4e4c3549.png)

Maybe an unrelated issue but even when toggling hints on my upper-right monitor without fullscreen, I get very weird hints placement:
![not-fullscreen-misplaced-hints](https://user-images.githubusercontent.com/16673538/103665257-82400880-4f73-11eb-8a7a-badd8ef665b7.png)

If I can add more details to describe my problem, please let me know, I'll gladly help !

**Comment by dexterleng** [comment]
Can replicate. Looks like fetching the screen frame through `NSScreen.main` returns the main display rather than the "focused" display when the application is in full screen mode.
