### ISSUE TITLE
Hints appear at bottom of upper display instead of in fullscreen app on lower display

### ISSUE THREAD

**Issue by nriley** [dexterleng/vimac#308]
I have two displays configured as follows:

![image](https://user-images.githubusercontent.com/68303/107268840-b9905200-6a16-11eb-95f4-f39f7bb257a9.png)

When I am using a full screen app on the lower display and invoke Vimac's hint mode, all the hints for the full screen app's window appear at the bottom of the upper/main display:

<img width="926" alt="image" src="https://user-images.githubusercontent.com/68303/107269329-74205480-6a17-11eb-8db2-2ee8b10cdca6.png">

If I move the lower display to the left of the upper/main display, then hints appear in the correct position:

<img width="619" alt="image" src="https://user-images.githubusercontent.com/68303/107269395-8bf7d880-6a17-11eb-88cc-030c0d86fc31.png">

**Comment by dexterleng** [comment]
@nriley 

Are you on the latest version:
![Screenshot 2021-02-13 at 12 28 57 AM](https://user-images.githubusercontent.com/34204380/107794481-76c1d780-6d92-11eb-98bd-c602af318189.png)

if so, do you happen to have **Displays have separate Spaces** disabled?

![Screenshot 2021-02-13 at 12 28 27 AM](https://user-images.githubusercontent.com/34204380/107794421-6578cb00-6d92-11eb-80bc-390446a7db45.png)

**Comment by dexterleng** [comment]
I can't seem to replicate this problem with **DIsplays have separate Spaces** enabled. Does it happen for all applications?

**Comment by nriley** [comment]
Yes, I am on version 0.3.15. Should also mention I'm on macOS 10.14.6, not sure why I didn't put that in my first message!

Yes, "Displays have separate Spaces" is turned on.

I tried with both OneNote and Safari previously. I also just tried with a Finder window and the same thing happens.  Please note that you have to be in full screen mode with a window — if it's not in full screen mode it's fine.

**Comment by dexterleng** [comment]
I am able to replicate this problem.

**Comment by dexterleng** [comment]
Should be fixed in the latest update. Do reopen if you still encounter this issue.

**Comment by nriley** [comment]
Working great, thanks!
