### ISSUE TITLE
Support exclude application

### ISSUE THREAD

**Issue by hanh090** [dexterleng/vimac#310]
Currently, I am binding `Ctrl-F` for hint mode, it is convenient to me because it nearly same config with Vimium config (`f` and `F`). However, it was override some keybinding from Vim. 
Therefore, can we support an option to exclude specific application from hint mode? 
For example, when I am in Vim and press hot key, hint mode do not appear. In other apps, it works as normal

One of example from AltTab app:
<img width="583" alt="Screen Shot 2021-02-14 at 21 21 27" src="https://user-images.githubusercontent.com/3643657/107879318-b9a6bb00-6f0a-11eb-92de-878b9ec254a8.png">

**Comment by dexterleng** [comment]
There are several similar feature requests. Closing this in favor of #139
