### ISSUE TITLE
Force Keyboard Layout enabled by default

### ISSUE THREAD

**Issue by marcelotaube** [dexterleng/vimac#311]
Hi I installed vimac recently, If I am able to make this work it will be my mac navigation dream come true.
Currently I have an issue with the main feature of the tool. I use the keyboard shortcut "ctrl + space", then vimac efficiently shows me the hints next to each control. When i start typing the keys suggested the hints disappear and no control is activate at all, as if I had presses Ctrl + space again.
I have no idea what could be wrong. I am using vimac 0.3.15 on MacOs Catalina 10.16.7.
If you need more info would be happy to provide it.
Thanks

**Comment by dexterleng** [comment]
What keyboard input are you using?

**Comment by marcelotaube** [comment]
I am using an external keyboard through USB, its the microsoft natural ergonomics keyboard.
But somehow your question helped me greatly and the penny dropped, so the mystery seems solved. Eureka!
I am happy now with the product.

About the issue:
I saw that vimac had chosen by default to force an hebrew keyboard layout while interpreting the keystokes, so even when i was seeing the hints with english letters, and even in the mac input menu English was selected, my keystrokes were recognized as hebrew letters which have no meaning for Vimac.

So even if you could define this as behaviour as expected it could be confusing that vimac chooses a keyboard layout which do not contain the letters which displays in it hints. An improvement would be to ask first time before choosing a layout so i know this behaviour is activated. Another possible improvement would be to display a small banner if I press an unrecognised key, indicating me which input has Vimac received.

In any case, many, many thanks for this product, its such a wonderful surprise.

**Comment by dexterleng** [comment]
Strange - Force keyboard layout should not be enabled by default.

**Comment by marcelotaube** [comment]
Well, I cannot turn back time and see exactly what happened, maybe I inadvertently pressed some key which activated this, I cannot know since i was experimenting with keyboard navigation and I had opened the preferences dialog after i installed vimac, so I cannot be sure.
