### ISSUE TITLE
Non-native support - AXManualAccessibility vs AXEnhancedUserInterface

### ISSUE THREAD

**Issue by dexterleng** [dexterleng/vimac#325]
| Attribute        | Pro(s)           | Con(s)  |
| ------------- |:-------------:| -----:|
| AXEnhancedUserInterface | Emulates VoiceOver; All VoiceOver compatible apps will work with it | Breaks window positioning; Have to use compatible window switcher e.g.(Rectangle) |
| AXManualAccessibility | All Electron apps work without the window positioning problem | Only Electron apps work with it; Other apps must be modified to support the attribute |

**Comment by eret9616** [comment]
Vimac is an awesome app，and the experimental feature in the latest update is great

I'm using a window switcher named maxsnap, and when I active non-native support, it breaks the window position, 
![image](https://user-images.githubusercontent.com/12445095/110443723-333f5c80-80f7-11eb-9711-a07678c13238.png)


I've tried " Rectangle"，but I can't like that app.. and I tried all software from that app author

In maxSnap,  I set fn to hold to move window, and set option to hold to resize window，
I can hold the command key and use two-finger swipe  to make positioning, that's very comfort ，hope there will be a better solution to deal this problem...

**Comment by eret9616** [comment]
@dexterleng  

I've wrote an email to the developer of maxsnap

I notice  ​that people won't use window manager to control position and use vimac at the same time,

when I select "Non-native Support Enabled" the Chrome will support this feature, and then I can active vimac hint mode, then when I unclick "Non-ntaive Support Enabled"
, I can  use  my window  manager tool,

What if just disable this feature after active hintmode(after showing those characters,and automatically disable this feature), I think it won't slow too much

**Comment by dexterleng** [comment]
@eret9616 enabling this feature immediately before hint mode doesn't work because:

1. It takes some time for Chrome to set up all the Accessibility related plumbing
2. From my testing, the API for enabling accessibility on Chrome unblocks before AX is set up on Chrome, so there is a race condition where Chrome is queried before AX is set up.
