### ISSUE TITLE
Items on right side of menu bar are overdrawn

### ISSUE THREAD

**Issue by blackketter** [dexterleng/vimac#334]
Not sure if this is a Vimac issue, but the items on the right side of the menubar seem to be rendered over by the items that they cover:
<img width="243" alt="Screen Shot 2021-03-08 at 7 59 13 AM" src="https://user-images.githubusercontent.com/131679/110347219-3d713600-7fe5-11eb-8e7c-eb562595ff49.png">
I don't remember seeing this before 0.3.16.

**Comment by dexterleng** [comment]
Addressed in latest version!

**Comment by blackketter** [comment]
That was fast!  Thanks!
