### ISSUE TITLE
Not working on VS Code after update

### ISSUE THREAD

**Issue by tecnoloco** [dexterleng/vimac#342]
Even though the experimental option for non-native apps is enabled after the last update vimac hints aren't working anymore.

Vimac version 0.3.16.1 (27)

**Comment by dexterleng** [comment]
Hi! Check out the electron option in Experimental tab in Preferences.

**Comment by dexterleng** [comment]
Could you try relaunching the app? I noticed a bug where all the set up isn't done correctly if Accessibility isn't granted on launch. Fixed in #340.

**Comment by tecnoloco** [comment]
I don't see any new release with this fix. I relaunched the app and the hints keep failing on VS Code. Should I wait for the release?

**Comment by dexterleng** [comment]
Just to clarify, hint-mode works on native applications, but not VSCode, despite the non-native option being enabled?

> Should I wait for the release?

Nope, if Accessibility permissions are granted on launch it should be fine.

**Comment by dexterleng** [comment]
Does hint-mode work on VSCode for you when Electron-support is enabled?

**Comment by xj-m** [comment]
> Does hint-mode work on VSCode for you when Electron-support is enabled?

For version 0.3.16.1, It works after Electron-support is enabled

**Comment by tecnoloco** [comment]
@dexterleng Yes, it worked when Electron-support is enabled just like @xj-m mentioned. I thought it wasn´t required since the description in the Electron-support says that it is enough if the non-native support is enabled.

 I think this can be closed.

**Comment by dexterleng** [comment]
Hmm, that's strange, it should work if non-native support is enabled, since it supposedly emulates VoiceOver.

If it works in apps like Chrome/Firefox then perhaps screen reader support is somehow explicitly disabled in VScode through some preferences setting?

**Comment by tecnoloco** [comment]
@dexterleng Also correct. I had Screen Reader disabled (off).
