### ISSUE TITLE
Question on releases

### ISSUE THREAD

**Issue by minton** [dexterleng/vimac#349]
👋 Thanks for the great app! 👏

I have a question about the releases. On GitHub, the latest release is currently 0.3.9. However, the release on App Center is seven releases higher at 0.3.16. Do you still plan to release at GitHub or only through App Center?

**Comment by dexterleng** [comment]
I plan on only releasing it through AppCenter for now. I'll delete the old Github releases. Thanks for pointing it out!

**Comment by dexterleng** [comment]
Deleted the GitHub releases.
