### ISSUE TITLE
Feature request: Move mouse to grid position

### ISSUE THREAD

**Issue by benwoodward** [dexterleng/vimac#416]
I'm not sure if this is a terrible idea or amazing idea, but I've recently gone full keyboard-only mode and I've set up hotkeys for moving the mouse cursor around (for those 10% of the time scenarios where Vimac/Yabai/Vimmode.spoon/etc. doesn't work) using Karabiner. It's actually kinda fun and not as difficult as I thought it be. However, one thing that would make keyboard driven mouse movement ideal would be the ability to move the mouse cursor to a section of the screen and then use hotkeys for accurate positioning. 

Here's how it could work:

1. Press shortcut to activate grid
(Using Divvy to illustrate what the UI could look like)

![image](https://user-images.githubusercontent.com/1472981/115685874-bd443b80-a3ac-11eb-8f4d-cf54c607dd94.png)

2. Each grid item has a hint. Type hint to move mouse cursor to the center of the grid item. 

3. Number of grid item rows/columns configurable

**Comment by dexterleng** [comment]
This idea was brought up in #331 

Could you give Voice Control's show grid a try? It is the same idea but you navigate by voice. Personally I didn't like it as much as XEasyMotion [1], although its conceptually much closer to Vimac's current hint mode.

[1] https://github.com/h2ero/XEasyMotion?
