### ISSUE TITLE
Compatibility problem with Magnets app

### ISSUE THREAD

**Issue by bob-ortiz** [dexterleng/vimac#417]
I use Magnets to easily resize and move windows from one monitor to another, but when Vimac is running the Magnets commands bug and do not work accordingly. Vimac works perfectly though, but it is a little annoying taking into account Magnets and Vimac combine perfectly so that one rarely needs to interact with the mouse.

**Comment by dexterleng** [comment]
Do you have non-native support enabled?

**Comment by dexterleng** [comment]
If you have non-native support enabled, may I ask why? What non-native applications would you like to use Vimac on?

**Comment by bob-ortiz** [comment]
> Do you have non-native support enabled? If so you'll have to Rectangle or use Electron support instead.
I did have non-native support enabled because I thought that's what was needed for Vimac to work on other apps like Notion, Spotify, etc. I don't know what Rectangle is, but I activated Electron support and it worked perfectly! Both Magnets' commands and Vimac's work perfectly now.

**Comment by dexterleng** [comment]
> Notion, Spotify, etc. I don't know what Rectangle is, but I activated Electron support and it worked perfectly! Both Magnets' commands and Vimac's work perfectly now. Thank you! I think I didn't understand correctly the concept of "non-native" app.

Noted. In the upcoming release I have made the distinction clearer and discourage Non-native support (basically VoiceOver emulation)
