### ISSUE TITLE
First activated scroll area should be the largest scroll area

### ISSUE THREAD

**Issue by colossatr0n** [dexterleng/vimac#418]
I generally find that the largest scroll area in an application is where I scroll the most. It'd be helpful if the first scroll area selected when activating scroll mode was the largest scroll area in the application.

**Comment by dexterleng** [comment]
It is ordered by the largest area. Could you share examples where it isn't?

**Comment by colossatr0n** [comment]
Oh, interesting. I tried to recreate the issue but it's now working as it's supposed to. 

With Microsoft Outlook it was selecting the side panel first, but now it's selecting the largest window again.

This case can be closed. If I run into it again, I'll try to pinpoint it more exactly.

**Comment by dexterleng** [comment]
Could it be that the height of the "larger" window is short? Maybe ordering by width may be a better approach.

**Comment by colossatr0n** [comment]
Yes, the side panel was taller but not as wide and it was being selected. 

Width could be a better selection criteria than height, but sometimes it wouldn't. An example of when it wouldn't would be when using an IDE like IntelliJ, since you can open sub windows at the bottom of the IntelliJ instance that are wider than the main IntelliJ view. 

I think the best selection criteria would be a mixture of area and aspect ratio. That way, a tall narrow scroll area, which might have more area than the main scroll area wouldn't be picked first, since its aspect ratio isn't one that would be used for a main view.

**Comment by dexterleng** [comment]
> I think the best selection criteria would be a mixture of area and aspect ratio. 

Agreed.

**Comment by dexterleng** [comment]
Heres an idea to calculate a "score" to rank by:  `score = area / abs(height - width)`

**Comment by colossatr0n** [comment]
I like it. And if two areas have the same score, you could default to whichever has the largest area.
