### ISSUE TITLE
Firefox integration without "Emulate VoiceOver"

### ISSUE THREAD

**Issue by MahdiNazemi** [dexterleng/vimac#424]
@dexterleng Thank you very much for developing and maintaining this phenomenal piece of software. It's really a lifesaver.

[Now that Firefox supports VoiceOver](https://blog.mozilla.org/accessibility/voiceover-support-for-macos-in-firefox-87/), I was wondering if any updates need to be made to Vimac to enable hints for addons, bookmarks, etc.

**Comment by dexterleng** [comment]
Hey! Perhaps there is confusion between VoiceOver and Voice Control.  VoiceOver emulation takes a large perf hit and has weird side effects, so it is disabled by default.  Voice Control emulation is enabled by default, which Chrome supports but Firefox does not. 

I'll filed an issue to Firefox. https://bugzilla.mozilla.org/show_bug.cgi?id=1706870. I believe they have an accessibility roadmap and voice control support should hopefully be in there.

**Comment by dexterleng** [comment]
Hope this helps! Closing this because I don't think I can do anything about this. Consider submitting a patch to Firefox if this is important.
