### ISSUE TITLE
"Rotate hints" stopped working?

### ISSUE THREAD

**Issue by kiding** [dexterleng/vimac#425]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/1336881/116200694-9a7ea200-a773-11eb-8ed6-d3264fa5ea7a.png">

Using the above settings, I don't see hints rotating when pressing space. Tested before updating to the latest 0.3.19 so #420 (nice) should not be the cause.

**Comment by dexterleng** [comment]
The rotation is random rather than by overlapping clusters - have you tried rotating several times?

**Comment by kiding** [comment]
Sorry, my misunderstanding.
