### ISSUE TITLE
[Feature request]Need command+click 

### ISSUE THREAD

**Issue by eret9616** [dexterleng/vimac#439]
With modifier keys vimac can perform rightclick and double-click, but there is no command+ click, its often used.. when browsing in web open in new tab ..

**Comment by dexterleng** [comment]
This is a good point. I was thinking about optimizing the workflow to click on the first item of menu which is "Open in new tab" for links, but I totally forgot you can just command+click.

**Comment by dexterleng** [comment]
Closing since its a dup of #204.
