### ISSUE TITLE
Vimac Homepage can't download Zip file on Firefox, works in Chrome

### ISSUE THREAD

**Issue by robinkwilson** [dexterleng/vimac#440]
To repro current behavior
1. Open Firefox (on mac)
2. Go to https://vimacapp.com/
3. Fill in Email and click download
4. Nothing happens

Expected behavior
Click download, the zip file downloads! (Like in Chrome)

Suggested fixes
Quick fix: have a message under the download button mentioning it doesn't work in Firefox.
Make sure firefox download works! :)

Looking forward to using the product!

**Comment by dexterleng** [comment]
@robinkwilson Thanks so much for reporting! It should be fixed now. Let me know if it doesn't, and I hope you like Vimac!

I made the mistake of attaching the click listener to the submit button instead of the form, so the page immediately reloads (which doesn't happen on Chrome for some reason).
