### ISSUE TITLE
Idea: Mouse mode?

### ISSUE THREAD

**Issue by kiding** [dexterleng/vimac#441]
A mode to freely use mouse cursor with hjkl and click on the current position. I'd find this useful when reaching for elements that are:

1. Hints are not shown but actually clickable
    * Example: Slack on Safari
        <img width="237" alt="Screen Shot 2021-05-28 at 11 23 41 AM" src="https://user-images.githubusercontent.com/1336881/119920739-c75aea80-bfa7-11eb-921a-b9eaf6d47325.png">

1. Hints are shown but only sometimes
    * Example: Discord on Safari
        <img width="305" alt="Screen Shot 2021-05-28 at 11 26 58 AM" src="https://user-images.githubusercontent.com/1336881/119920747-caee7180-bfa7-11eb-90a4-6b7308bea5a0.png">

1. Hints are positioned slightly outside the clickable area
    * Example: https://rectangleapp.com on Safari
        <img width="331" alt="image" src="https://user-images.githubusercontent.com/1336881/119921223-96c78080-bfa8-11eb-8b9e-ce508aa668a6.png">

**Comment by blackketter** [comment]
Totally agree!  There's been some discussion of this in #331 along with other modes.

**Comment by kiding** [comment]
Just read through the thread, thanks! The proposal https://github.com/dexterleng/vimac/issues/331#issuecomment-797560992 looks quite promising. Let me close this issue for now.
