### ISSUE TITLE
Feature Request: Keep original mouse position on activate

### ISSUE THREAD

**Issue by justinnoel** [dexterleng/vimac#480]
This is a request similar to #116 but the reverse.

When I activate scrolling with Ctrl + J, the cursor is positioned to the center of the screen. I'd really love the option for the cursor position to remain where it started.

Why?

I **hate** mouseover effects in Slack and Discord from triggering while I scroll. So, I move the mouse to the top right corner of the scrollable area before scrolling. Then, as I scroll, I don't see all the mouseover effects. 

When scrolling with Vimac, the cursor starts in the center and scrolling causes all the mouseover effects. Since I can't see where the cursor really is, I have to manually move the mouse trying to find a safe area that 1) scrolls still and 2) doesn't trigger mouseover as much.

**Comment by keithgibson** [comment]
@justinnoel i don't think this version of the project is being maintained anymore. There's now a paid version of it called [Homerow](https://homerow.app/) that is being updated. Details here: https://github.com/dexterleng/vimac/issues/477#issuecomment-1166346687
