### ISSUE TITLE
Suggestion for homerow

### ISSUE THREAD

**Issue by xbladesub** [dexterleng/vimac#481]
Sometimes you can't get to some elements - there are no hints some reason. Is it possible to create some kind of grid over the entire screen with hints inside each cell? I think it would be useful in many cases. Simply enable/disable the grid with a shortcut. May be the idea is not new :)

**Comment by dexterleng** [comment]
I'll consider it! It might a bit slow since it will require 2-3 hints to click at the location, but worth experimenting with.
