### ISSUE TITLE
Show hints for extra menu bar items

### ISSUE THREAD

**Issue by dexterleng** [dexterleng/vimac#76]
<img width="606" alt="Screenshot 2019-11-22 at 5 06 16 PM" src="https://user-images.githubusercontent.com/34204380/69412742-7337d000-0d4a-11ea-8331-9faef4444ace.png">

**Comment by orthodoX** [comment]
Hi @dexterleng, I'm a huge fan of vimium, and recently Vimac as well. Awesome work so far! 
The only thing I noticed that it's missing so far is the support for menu bar items. Any ideas when this might be implemented?

**Comment by dexterleng** [comment]
Hi @orthodoX, I have been a bit busy with fixing bugs and school for the past few months. My school semester just ended so I can develop Vimac more actively now.

**Comment by dexterleng** [comment]
this is pretty high up on priority list so you can expect this soon^tm.

**Comment by dexterleng** [comment]
Feature has been merged. Look forward to it in the next release!
