### ISSUE TITLE
Add shadows to hints

### ISSUE THREAD

**Issue by dexterleng** [dexterleng/vimac#81]
Makes it easier to tell overlapping hints apart.

**Comment by narkkil** [comment]
I could give this a look if still needed.

**Comment by dexterleng** [comment]
@narkkil I did not work on this because this is a symptom of the hint querying for too much elements. Recent changes #413 #280 have reduced the no. of overlapping hints dramatically, and I've made the hint borders darker. Maybe there is some other benefit to shadows that I've missed?

**Comment by narkkil** [comment]
Thanks for your time! 

I don't think you've missed anything in regards to their visibility in my opinion. Originally I was looking to reproduce a bug I was experiencing (in short: relating to hint overlays disappearing in some rare occasions but I don't have real clues for that yet), and thought of maybe contributing something small in the same go while I was looking through the codebase.

Unfortunately I think the window for working on these recent discussions on my part has closed for the time being, but in case I can reproduce the bug somehow I'll be sure to let you know.

**Comment by dexterleng** [comment]
@narkkil got it. closing this for now.
