### ISSUE TITLE
Make Preferences prettier

### ISSUE THREAD

**Issue by dexterleng** [dexterleng/vimac#84]
It would be great if it the settings were grouped by General, Hint Mode, and Scroll Mode

**Comment by ogirginc** [comment]
Is this how it is suppose to look on Catalina (10.15.14)?

<img width="612" alt="Screenshot 2020-03-29 at 11 20 18" src="https://user-images.githubusercontent.com/7466873/77844447-aafacc80-71af-11ea-8b9c-154a233eab50.png">

**Comment by dexterleng** [comment]
Yep 😬

**Comment by dexterleng** [comment]
Fixed in v0.3.10!
